before_install:
  - ./.travis_before_install.sh
language: cpp
compiler: clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - bison
      - cmake
      - flex
      - google-perftools
      - libpcap-dev
      - libssl-dev
      - python-dev
      - swig
      - zlib1g-dev
